name: 上传组件
on: 
    push:
        tags: ['v*']
    workflow_dispatch:

jobs:
    upload:
        uses: smalllin0/my-ci-templates/.github/workflows/upload.yml@master
        with:   
            namespace: smallin
        secrets:
            IDF_COMPONENT_API_TOKEN: ${{ secrets.IDF_COMPONENT_API_TOKEN }}